### PR TITLE
Added support for aarch64

### PR DESCRIPTION
**Pull request by marcovolpato00**
I've added support for aarch64 so it's possible to run the image on boards with such architecture.

### CODE REVIEW

**Comment by JC5** [comment]
Are you kidding me, I am just right now experimenting with a multi-arch build :grin:

Could you do me a huge favour. Cancel this PR because you clashed with mine not 4 minutes ago. Resubmit (look at my changes) and see if it's still necessary. If so, feel free to create another PR.

I can't believe this is happening 😅

**Comment by JC5** [comment]
Here is the build on Travis, it's not even finished 😆 

https://travis-ci.com/JC5/firefly-iii-base-image/builds/134582315

**Comment by marcovolpato00** [comment]
I'll look at your changes. Can't believe we were working on it at the same time 😅

**Comment by JC5** [comment]
I just pushed my final commit that should take care of the manifest. I am trying to do the following:

- triple parallel build instead of serial build
- update the manifest from each build, so that even when they're out of order the final image will have 3 images in the manifest.

**Pull request closed without merging**
